### ISSUE TITLE
Respecing does not work.

### ISSUE THREAD

**Issue by Warren1001** [haxifix/PlugY#1]
I can confirm that "ActiveSkillsUnassignment" does = 1.
To detail, clicking the 'X' at the top right of the Skill Tree does nothing. I can hear the audio indicator that it has been pressed, but no skills are changed at all. This goes for completely new characters and characters created in 1.13.

**Comment by Warren1001** [comment]
[PlugY.log](https://github.com/haxifix/PlugY/files/4706464/PlugY.log)
pre-existing character (HC)

[PlugY.log](https://github.com/haxifix/PlugY/files/4706465/PlugY.log)
new character AFTER installing new plugy.

all i did was load in, click the respec button TWICE on both characters. on the second character, i logged out before sending the PlugY.log

**Comment by haxifix** [comment]
I have just updated the mod.  Please see if the issue is fixed.

**Comment by Warren1001** [comment]
that solved it, nice work
