### ISSUE TITLE
tcp/ip games crashes cant join game v1.14d

### ISSUE THREAD

**Issue by alikhan866** [haxifix/PlugY#16]
I am using diablo 2  version `1.14d`  hosting the server works but my friends cannot join my game and then the PC crashes 

Similarly i cant join any other game hosted by my friends

**Comment by skylight102** [comment]
Use hamachi

On 3 Oct 2020, at 15:29, Ali Khan <notifications@github.com> wrote:

﻿

I am using diablo 2 version 1.14d hosting the server works but my friends cannot join my game and then the PC crashes

Similarly i cant join any other game hosted by my friends

**Comment by alikhan866** [comment]
hamachi ?

**Comment by Salvoxia** [comment]
I think this might be a duplicate of #2

**Comment by alikhan866** [comment]
@Salvoxia  yes it is im closing the issue thanks its working now :) .. hope the team fixes the bug in the future
