### ISSUE TITLE
Missing dll?

### ISSUE THREAD

**Issue by Tiggrrr** [haxifix/PlugY#19]
Copied and extracted the zip into the d2 directory. Click PlugY, and am told VCRUNTIME140.dll is not found.

**Comment by ChaosMarc** [comment]
you need to install this: https://www.microsoft.com/download/details.aspx?id=48145

**Comment by Tiggrrr** [comment]
For some reason, that link doesn't load. However I navigated to microsoft's websight and got their 2015-2019 redistributible for x64, and it made no difference. I then got the same one for x86, and it seems to be working fine. Thank you!
