### ISSUE TITLE
Bad index fct on fresh DII+LOD install (1.14b)

### ISSUE THREAD

**Issue by FedericoRocca** [haxifix/PlugY#8]
PlugY.log:
[PlugY.log](https://github.com/haxifix/PlugY/files/4944643/PlugY.log)

<----------------------------------------------->

		A Plugin by Yohann & haxifix
		version 12.00

<---------- Starting Diablo II Plugin ---------->

***** Get D2 Modules address and version *****
Game.exe loaded at:	00400000 (1.14b)

Bad index fct 10057 for 00400000
...

**Comment by FedericoRocca** [comment]
After updating this fresh install to 1.14d PlugY its working as intended. Is this ok?

**Comment by Salvoxia** [comment]
Yes, this version only works with 1.14d.

**Comment by FedericoRocca** [comment]
Great to know, thanks.
